try:
    print(x)
except:
    print("Algum erro ocorreu")
finally:
    print("O try e except foram finalizados")